# Generated by Django 5.2.17 on 2026-09-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopallocation',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='schedule_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='time_period',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], max_length=10),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='week_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='week_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='workshop',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workshopallocation',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopallocation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopallocation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
