# Generated by Django 5.2.17 on 2026-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workshopallocation_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopallocation',
            name='venue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
