# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workshopallocation_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecourse',
            name='course_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmecourse',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='programmecourse',
            options={
                'ordering': ['programme__code', 'semester', 'course_code'],
                'unique_together': {('programme', 'course_code')},
            },
        ),
    ]