# Generated by Django 5.2.17 on 2026-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programmecourse_course_name_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('IMPORT', 'Imported'), ('ASSIGN', 'Assigned'), ('REMOVE', 'Removed')], max_length=20)),
                ('resource', models.CharField(blank=True, max_length=50)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
