# Generated by Django 5.2.17 on 2026-09-22 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('IMPORT', 'Imported'), ('ASSIGN', 'Assigned'), ('REMOVE', 'Removed'), ('CLEAR', 'Cleared')], max_length=20),
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=50)),
                ('import_title', models.CharField(max_length=100)),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Completed with issues'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import history',
                'verbose_name_plural': 'Import history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_type', '-created_at'], name='core_import_import__c51938_idx')],
            },
        ),
    ]
