# Generated by Django 5.2.3 on 2026-09-26 13:36

import collections
import json

import django.db.models.deletion
from django.db import migrations, models


def _normalise(value):
    """Same canonical form as ``core.models.normalise_course_code``."""
    return " ".join(str(value or "").strip().split()).upper()


def _pick_name(counter):
    """The one name to keep for a code, chosen deterministically.

    The most frequent spelling wins; ties break on the shortest then
    alphabetically, so re-running the migration on the same data always picks
    the same name. The losing spellings are kept on the Course record as
    ``name_variants`` so the coordinator can review the choice.
    """
    ranked = sorted(
        counter.items(), key=lambda kv: (-kv[1], len(kv[0]), kv[0])
    )
    return ranked[0][0], [name for name, _ in ranked[1:]]


def forwards(apps, schema_editor):
    """Create one shared Course per course code and point the programme links at it.

    Programme rows that spell the same code differently (" mt161" vs "MT161")
    are merged into one course. Where the *names* disagree the pick is
    deterministic (see ``_pick_name``) and the alternatives are recorded, not
    discarded. No requirements are inferred here: a course with no
    requirement rows is exactly the "requirement not configured" case the
    allocation review flags for the coordinator.
    """
    Course = apps.get_model("core", "Course")
    ProgrammeCourse = apps.get_model("core", "ProgrammeCourse")

    names_by_code = collections.defaultdict(collections.Counter)
    codes_seen = set()
    for row in ProgrammeCourse.objects.all().values("id", "course_code", "course_name"):
        code = _normalise(row["course_code"])
        if not code:
            continue
        codes_seen.add(row["id"])
        name = (row["course_name"] or "").strip()
        if name:
            names_by_code[code][name] += 1

    courses = {}
    for code in sorted(names_by_code):
        name, variants = _pick_name(names_by_code[code])
        courses[code] = Course.objects.create(
            code=code,
            name=name,
            name_variants=json.dumps(variants) if variants else "",
        )

    for row in ProgrammeCourse.objects.filter(id__in=codes_seen).iterator():
        code = _normalise(row.course_code)
        course = courses.get(code)
        if course is None:
            # A row whose code was blank: leave it unlinked rather than guess.
            continue
        row.course_id = course.pk
        row.course_code = code
        row.course_name = course.name
        row.save(update_fields=["course_id", "course_code", "course_name"])


def backwards(apps, schema_editor):
    """Unlink the programme rows. Course records are kept (PROTECT, shared)."""
    apps.get_model("core", "ProgrammeCourse").objects.update(course=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activitylog_action_importhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_variants', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='programmecourse',
            name='course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SEMINAR', 'Seminar'), ('TUTORIAL', 'Tutorial'), ('PRACTICAL', 'Practical'), ('ALL', 'All configured activities')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('APPLIED', 'Applied'), ('REVERTED', 'Reverted')], default='PREVIEWED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('search_limit_hit', models.BooleanField(default=False)),
                ('assigned', models.IntegerField(default=0)),
                ('moved', models.IntegerField(default=0)),
                ('retained', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
                ('unresolved', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_runs', to='core.semester')),
            ],
            options={
                'verbose_name': 'Allocation run',
                'verbose_name_plural': 'Allocation runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Added'), ('REMOVE', 'Removed')], max_length=10)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('activity_type', models.CharField(blank=True, max_length=20)),
                ('before', models.TextField(blank=True)),
                ('after', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_changes', to='core.studentgroup')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_changes', to='core.session')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.allocationrun')),
            ],
            options={
                'ordering': ['run', 'course_code', 'activity_type', 'group__code'],
            },
        ),
        migrations.AddField(
            model_name='programmecourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programme_courses', to='core.course'),
        ),
        migrations.CreateModel(
            name='CourseActivityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('TUTORIAL', 'Tutorial'), ('SEMINAR', 'Seminar'), ('PRACTICAL', 'Practical'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requirements', to='core.course')),
            ],
            options={
                'ordering': ['course__code', 'activity_type'],
            },
        ),
        migrations.AddIndex(
            model_name='allocationrun',
            index=models.Index(fields=['semester', '-created_at'], name='core_alloca_semeste_7062c0_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationchange',
            index=models.Index(fields=['run', 'action'], name='core_alloca_run_id_697466_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseactivityrequirement',
            unique_together={('course', 'activity_type')},
        ),
        migrations.RunPython(forwards, backwards),
    ]
