# Generated by Django 5.2.17 on 2026-09-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_requirements_and_allocation_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Checked on at most one semester: the term staff and students are working in. Left unset, pages fall back to the newest semester that holds data.'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='core_semester_only_one_current'),
        ),
    ]
