# Generated by Django 5.2.17 on 2026-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_semester_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='algorithm',
            field=models.CharField(choices=[('smart', 'Smart (Min-Conflicts)'), ('advanced', 'Advanced (OR-Tools)')], default='smart', max_length=20),
        ),
    ]
