# Generated by Django 5.2.17 on 2026-09-29 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_allocationrun_algorithm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRunMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('candidates_examined', models.IntegerField(blank=True, null=True)),
                ('backtracks', models.IntegerField(blank=True, null=True)),
                ('requirements_processed', models.IntegerField(blank=True, null=True)),
                ('search_limit_hit', models.BooleanField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.allocationrun')),
            ],
            options={
                'verbose_name': 'Allocation run metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(default='1.0.0', max_length=40)),
                ('thresholds_json', models.TextField(blank=True)),
                ('summary_json', models.TextField(blank=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('pdf_path', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('progress', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generation_seconds', models.FloatField(blank=True, null=True)),
                ('config_path', models.CharField(blank=True, max_length=400)),
                ('allocation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='core.allocationrun')),
                ('comparison_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_reports', to='audit.auditreport')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit report',
                'verbose_name_plural': 'Audit reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['allocation_run', '-version'], name='audit_audit_allocat_473d14_idx'), models.Index(fields=['status'], name='audit_audit_status_99cb2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('allocation_run', 'version'), name='audit_report_version_unique')],
            },
        ),
    ]
